import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Elvoit!</a>
        </h1>

        <p className={styles.description}>
          Get started by creating your first Event{' '}
          <code className={styles.code}>for FREE!!</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Manage votings &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Recieve Payments &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
          <Link href="/login">
            <a className={styles.card}>
              <h2>Login your account &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>`
            </a>
          </Link>

          <Link href="/register">
            <a className={styles.card}>
              <h2>Create free account &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>`
            </a>
          </Link>
        </div>
      </main>
    </div>
  )
}
